# ML Lab 1



In [ ]:
# write a program to create a numpy array using a python list.
# display the array and print the shape and datatype of array.

import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print("shape: ", arr1.shape)
print("datatype: ", arr1.dtype)

[1 2 3 4 5]
shape:  (5,)
datatype:  int64


In [ ]:
# write a program to create a 3x3 matrix of 0s and create a 2x5 matrix of 1s.
# print both the matrices and their shape.

matrix0 = np.zeros((3,3))
matrix1 = np.ones((2,5))

print("matrix 1 shape: ", matrix0.shape)
print(matrix0)

print("\nmatrix 2 shape: ", matrix1.shape)
print(matrix1)

matrix 1 shape:  (3, 3)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

matrix 2 shape:  (2, 5)
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# write a program to create a numpy array of numbers from 1 to 12.
# reshape the array into a 3x4 matrix. display the original and reshaped
# array along with their shapes.

og_arr = np.arange(1, 13)
print("original array shape: ", og_arr.shape)
print(og_arr)

reshaped_arr = og_arr.reshape(3,4)
print("\nreshaped array shape: ", reshaped_arr.shape)
print(reshaped_arr)

original array shape:  (12,)
[ 1  2  3  4  5  6  7  8  9 10 11 12]

reshaped array shape:  (3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# write a program to create a numpy array of 10 random integers.
# find the minimum, maximum, mean and sum of elements of the array.

arr4 = np.random.randint(1, 100, 10)
print(arr4)
print("minimum: ", arr4.min())
print("maximum: ", arr4.max())
print("mean: ", arr4.mean())
print("sum: ", arr4.sum())

[49 28 80 20  1 57 40  8 34 68]
minimum:  1
maximum:  80
mean:  38.5
sum:  385


In [ ]:
# write a program to create a dataframe using a dictionary containing student name and marks.
# display the data frame and print the datatypes of each column.

import pandas as pd
data = {
    "name": ["Gayathri", "Ansh", "Vedica", "Ishika"],
    "marks": [100, 100, 99, 69]
}

df = pd.DataFrame(data)

print(df)
print("\ndatatypes: ")
print(df.dtypes)

       name  marks
0  Gayathri    100
1      Ansh    100
2    Vedica     99
3    Ishika     69

datatypes: 
name     object
marks     int64
dtype: object


In [ ]:
# write a program to read a csv file and display the first and last five records.
from google.colab import files
uploaded = files.upload()

Saving test_data.csv to test_data.csv


In [ ]:
df = pd.read_csv("test_data.csv")
print("first 5 records: ")
print(df.head())
print("\nlast 5 records: ")
print(df.tail())

first 5 records: 
       Name  Marks   Age  Unnamed: 3  Unnamed: 4
0  Gayathri  100.0  20.0         NaN         NaN
1      Ansh  100.0  20.0         NaN         NaN
2    Vedica   98.0  23.0         NaN         NaN
3    Aarush   99.0  21.0         NaN         NaN
4    Sadhvi   96.0  20.0         NaN         NaN

last 5 records: 
         Name  Marks   Age  Unnamed: 3  Unnamed: 4
9      Soumya   92.0  20.0         NaN         NaN
10     Khushi   93.0  19.0         NaN         NaN
11    Trishty   80.0  19.0         NaN         NaN
12  Chaitanya   70.0  20.0         NaN         NaN
13    Advaith   97.0  19.0         NaN         NaN


In [ ]:
# load dataset and show rows, columns, missing values

df = pd.read_csv("test_data.csv")
print("number of rows: ", df.shape[0])
print("number of rows: ", df.shape[1])
print("missing values  in each column: ")
print(df.isnull().sum())

number of rows:  14
number of rows:  5
missing values  in each column: 
Name           0
Marks          1
Age            1
Unnamed: 3    14
Unnamed: 4    14
dtype: int64


In [ ]:
# write a program to read a csv file into a dataframe and
# display the statistical summary using describe method. interpret mean,
# standard deviation and minimum maximum values.

df = pd.read_csv("test_data.csv")
summary = df.describe()
print(summary)

            Marks        Age  Unnamed: 3  Unnamed: 4
count   13.000000  13.000000         0.0         0.0
mean    91.538462  19.769231         NaN         NaN
std      9.297091   1.235168         NaN         NaN
min     70.000000  18.000000         NaN         NaN
25%     90.000000  19.000000         NaN         NaN
50%     95.000000  20.000000         NaN         NaN
75%     98.000000  20.000000         NaN         NaN
max    100.000000  23.000000         NaN         NaN
